
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelReserve1?serverTimezone=UTC
    username: root
    password: teacher
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: consumer-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka


debug: true
logging:
  level:
    org.springframework: WARN





